#!/bin/bash

#PBS -N jacobi
#PBS -o jacobi.out
#PBS -joe
#PBS -m a
#PBS -q teaching
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:30:00

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID

export KMP_AFFINITY=compact
export OMP_WAIT_POLICY=active
export KMP_BLOCKTIME=0
export OMP_DYNAMIC=1
export OMP_NUM_THREADS=16
#amplxe-cl -quiet -collect hotspots -result-dir r001hs 
./jacobi --norder 4000 --iterations 20000

